### ISSUE TITLE
Database Glitch (Im almost connected to the server though)

### ISSUE THREAD

**Issue by Jazhan** [SIU-CS/Direct_Democracy-production#18]
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by akohli96** [comment]
Check your code syntax at exactly the line it says
